# Generated by Django 3.2.9 on 2021-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Состoяние публикации'),
        ),
    ]
