# Generated by Django 3.2.8 on 2021-10-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
